<<<<<<< HEAD
# fly.toml app configuration file generated for data-sec-analyzer-fra on 2025-06-02T01:17:59+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'data-sec-analyzer-fra'
primary_region = 'fra'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
=======
app = "data-security-analyzer"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
>>>>>>> 12cc0bac3eae74c96737f6d2fbb0d8af5f1a6dc1
