# Generated by Django 4.2.21 on 2025-05-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantinedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('original_path', models.CharField(max_length=255)),
                ('quarantine_path', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('quarantine_time', models.DateTimeField(auto_now_add=True)),
                ('scan_type', models.CharField(max_length=50)),
                ('hash', models.CharField(max_length=64)),
                ('size', models.BigIntegerField()),
            ],
        ),
    ]
