# Generated by Django 4.2.21 on 2025-05-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarantinedfile',
            options={'ordering': ['-quarantine_time']},
        ),
        migrations.RemoveField(
            model_name='quarantinedfile',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='quarantinedfile',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='quarantinedfile',
            name='scan_type',
        ),
        migrations.RemoveField(
            model_name='quarantinedfile',
            name='size',
        ),
        migrations.AddField(
            model_name='quarantinedfile',
            name='malware_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quarantinedfile',
            name='scan_tool',
            field=models.CharField(default='clamscan', max_length=50),
        ),
        migrations.AddField(
            model_name='quarantinedfile',
            name='status',
            field=models.CharField(default='quarantined', max_length=20),
        ),
        migrations.AlterField(
            model_name='quarantinedfile',
            name='original_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quarantinedfile',
            name='quarantine_path',
            field=models.TextField(),
        ),
    ]
