# Generated by Django 4.2.21 on 2025-05-25 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_quarantinedfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinedfile',
            name='detected_by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quarantinedfile',
            name='file_hash',
            field=models.CharField(default='unknown', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarantinedfile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarantinedfile',
            name='threat_level',
            field=models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='quarantinedfile',
            name='original_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='quarantinedfile',
            name='quarantine_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='quarantinedfile',
            name='quarantine_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quarantinedfile',
            name='scan_tool',
            field=models.CharField(max_length=100),
        ),
    ]
