# Generated by Django 4.2.21 on 2025-05-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_quarantinedfile_detected_by_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1000)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_directory', models.BooleanField(default=False)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('permissions', models.CharField(blank=True, max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_quarantined', models.BooleanField(default=False)),
                ('quarantine_date', models.DateTimeField(blank=True, null=True)),
                ('scan_status', models.CharField(default='pending', max_length=20)),
                ('scan_result', models.TextField(blank=True)),
                ('scan_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['path'], name='list_file_path_eb6f39_idx'), models.Index(fields=['is_directory'], name='list_file_is_dire_9ad060_idx'), models.Index(fields=['is_quarantined'], name='list_file_is_quar_df44d5_idx'), models.Index(fields=['scan_status'], name='list_file_scan_st_f26406_idx')],
            },
        ),
    ]
