# Generated by Django 4.2.21 on 2025-05-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuarantinedFile',
        ),
    ]
