# Generated by Django 5.2.1 on 2025-06-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_delete_quarantinedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name'], 'verbose_name': 'Dosya', 'verbose_name_plural': 'Dosyalar'},
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='list_file_is_dire_9ad060_idx',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='is_directory',
            new_name='is_dir',
        ),
        migrations.AddField(
            model_name='file',
            name='accessed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='permissions',
            field=models.CharField(max_length=10),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_dir'], name='list_file_is_dir_aeaf48_idx'),
        ),
    ]
