import re
import os
from django.conf import settings

# Global regex patterns for sensitive data detection
sensitive_patterns = {
    'TC Kimlik': r'\b[1-9][0-9]{10}\b',
    'Telefon': r'(?:\+90|0)?\s*?\(?5\d{2}\)?[\s-]?\d{3}[\s-]?\d{2}[\s-]?\d{2}',
    'E-posta': r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b',
    'Kredi Kartı': r'\b(?:\d[ -]*?){13,16}\b',
    'IBAN': r'TR\d{2}\s?(\d{4}\s?){5}\d{2}',
    'Şifre': r'(?:password|passwd|pwd)\s*=\s*["\']?[^"\']+["\']?',
    'API Anahtarı': r'(?:api[_-]?key|apikey)\s*=\s*["\']?[^"\']+["\']?',
    'Gizli Anahtar': r'(?:secret[_-]?key|private[_-]?key)\s*=\s*["\']?[^"\']+["\']?',
    'AWS Anahtarı': r'AKIA[0-9A-Z]{16}',
    'Google API Anahtarı': r'AIza[0-9A-Za-z-_]{35}',
    'SSH Anahtarı': r'-----BEGIN (?:RSA|DSA|EC|OPENSSH) PRIVATE KEY-----',
    'SSL Sertifikası': r'-----BEGIN CERTIFICATE-----',
    'Veritabanı Bağlantısı': r'(?:mysql|postgresql|mongodb|redis)://[^:\s]+:[^@\s]+@[^:\s]+:\d+',
    'JWT Token': r'ey[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*',
    'OAuth Token': r'ya29\.[0-9A-Za-z\-_]+',
    'IPv4 Adresi': r'\b(?:\d{1,3}\.){3}\d{1,3}\b',
    'IPv6 Adresi': r'(?:[A-F0-9]{1,4}:){7}[A-F0-9]{1,4}',
    'MAC Adresi': r'(?:[0-9A-Fa-f]{2}[:-]){5}(?:[0-9A-Fa-f]{2})',
    'Kurum Sicil No': r'\b[0-9]{10}\b',
    'Vergi No': r'\b[0-9]{10}\b',
    'SGK No': r'\b[0-9]{10}\b',
    'Pasaport No': r'[A-Z][0-9]{8}',
    'Ehliyet No': r'[A-Z][0-9]{8}',
    'Kredi Kartı CVV': r'\b[0-9]{3,4}\b',
    'Kredi Kartı Son Kullanma': r'\b(?:0[1-9]|1[0-2])/(?:[0-9]{2})\b',
    'Adres': r'(?:Mahalle|Sokak|Cadde|Bulvar|Avenue|Street|Road)\s+[A-Za-zğüşıöçĞÜŞİÖÇ\s]+(?:No|No\.)?\s*[0-9]+',
    'Doğum Tarihi': r'\b(?:0[1-9]|[12][0-9]|3[01])/(?:0[1-9]|1[0-2])/(?:19|20)[0-9]{2}\b',
    'Hesap Numarası': r'\b[0-9]{10,26}\b',
    'SWIFT Kodu': r'[A-Z]{6}[A-Z0-9]{2}(?:[A-Z0-9]{3})?',
    'BIC Kodu': r'[A-Z]{6}[A-Z0-9]{2}(?:[A-Z0-9]{3})?'
}

# Centralized regex patterns in Python dictionary format (Comprehensive)
ALL_REGEX_PATTERNS_BACKEND = {
    'personalInfo': [
        {'subcategory': 'TC Kimlik Numarası', 'pattern': r'\b[1-9]\d{10}\b'},
        {'subcategory': 'Vergi Kimlik Numarası', 'pattern': r'\b\d{10}\b'},
        {'subcategory': 'Telefon Numarası (Mobil)', 'pattern': r'\b05\d{9}\b'},
        {'subcategory': 'Telefon Numarası (Sabit Hat)', 'pattern': r'\b0[2-4]{1}\d{9}\b'},
        {'subcategory': 'E-posta Adresi (Kurumsal)', 'pattern': r'\b[A-Za-z0-9._%+-]+@[a-z0-9.-]+\.(com|net|org|gov|edu|tr)\b'},
        {'subcategory': 'E-posta Adresi (Kişisel – Gmail, Yahoo, vs.)', 'pattern': r'\b[A-Za-z0-9._%+-]+@(gmail|yahoo|hotmail|outlook)\.(com|net|tr)\b'},
        {'subcategory': 'Doğum Tarihi (YYYY-MM-DD)', 'pattern': r'\b(19|20)\d{2}[-/.]?(0[1-9]|1[0-2])[-/.]?(0[1-9]|[12][0-9]|3[01])\b'},
        {'subcategory': 'Doğum Tarihi (DD.MM.YYYY)', 'pattern': r'\b(0[1-9]|[12][0-9]|3[01])[.](0[1-9]|1[0-2])[.](19|20)\d{2}\b'},
        {'subcategory': 'IP Adresi (IPv4)', 'pattern': r'\b(?:(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\b'},
        {'subcategory': 'IP Adresi (IPv6)', 'pattern': r'\b(?:[A-Fa-f0-9]{1,4}:){7}[A-Fa-f0-9]{1,4}\b'},
        {'subcategory': 'MAC Adresi', 'pattern': r'\b([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})\b'},
        {'subcategory': 'Pasaport Numarası', 'pattern': r'\b[A-Z0-9]{6,9}\b'},
        {'subcategory': 'Kimlik Seri No (TR Kimlik Kartı Arka)', 'pattern': r'\b[A-Z]{2}\d{6}\b'},
        {'subcategory': 'Plaka Numarası (TR Formatı)', 'pattern': r'\b\d{2}\s?[A-Z]{1,3}\s?\d{2,4}\b'},
        {'subcategory': 'Ehliyet Numarası', 'pattern': r'\b\d{5,10}[A-Z]{0,2}\b'},
        {'subcategory': 'Öğrenci Numarası', 'pattern': r'\b\d{7,12}\b'},
        {'subcategory': 'Baba Adı or Anne Adı', 'pattern': r'\b(Baba Adı:?|Anne Adı:?)\s?[A-ZÇĞİÖŞÜ][a-zçğıöşü]+\b'},
        {'subcategory': 'Uyruğu', 'pattern': r'\b(T.C.?|Türkiye Cumhuriyeti|Yabancı)\b'},
        {'subcategory': 'Cinsiyet Bilgisi', 'pattern': r'\b(Erkek|Kadın|Diğer)\b'},
        {'subcategory': 'Medeni Hali', 'pattern': r'\b(Bekar|Evli|Boşanmış|Dul)\b'},
        {'subcategory': 'Kan Grubu', 'pattern': r'\b([ABO]{1,2})[+-]\b'},
        {'subcategory': 'Kişisel Kodu (Unique ID)', 'pattern': r'\bUID[-:]?\d{5,10}\b'},
        {'subcategory': 'Sosyal Güvenlik Numarası (SSN – US)', 'pattern': r'\b\d{3}-\d{2}-\d{4}\b'},
        {'subcategory': 'IBAN Üzerinden Ad Soyad Eşleştirme', 'pattern': r'\bTR\d{2}\s?\d{4}\s?\d{4}\s?\d{4}\s?\d{4}\s?\d{0,2}\b'},
        {'subcategory': 'Kullanıcı Adı', 'pattern': r'\buser(Name)?[:=]?\s?[a-zA-Z0-9_]+\b'},
        {'subcategory': 'Şifre', 'pattern': r'\bpass(word)?[:=]?\s?.{6,}\b'},
        {'subcategory': 'Göçmenlik/Dosya Numarası', 'pattern': r'\b[A-Z]{1,3}\d{6,9}\b'},
        {'subcategory': 'Fotoğraftan EXIF verisindeki Kişi Adı', 'pattern': r'\b(PersonName|Subject)[:=]?\s?[A-ZÇĞİÖŞÜ][a-zçğıöşü]+\b'},
        {'subcategory': 'Konum Etiketi (Metadata\'dan)', 'pattern': r'\bGPS[-: ]?(Latitude|Longitude)[-: ]?\d{1,3}\.\d+\b'},
        {'subcategory': 'QR Kod içinde saklanan kimlik verisi', 'pattern': r'\bQRID[:=]?\d{6,10}\b'},
        {'subcategory': 'Barkod içeriğiyle eşleşen kişisel tanımlar', 'pattern': r'\bBARCODE[:=]?[A-Z0-9]{8,13}\b'},
        {'subcategory': 'Tıbbi Tanıdaki Hasta Adı (Simplified)', 'pattern': r'\b(Hasta Adı:?)\s?[A-ZÇĞİÖŞÜ][a-zçğıöşü]+\b'},
        {'subcategory': 'Kargo Etiketi Üzerindeki Ad-Soyad', 'pattern': r'\bGönderici[:=]?\s?[A-ZÇĞİÖŞÜ][a-zçğıöşü]+\s[A-ZÇĞİÖŞÜ][a-zçğıöşü]+\b'},
        {'subcategory': 'Sosyal Medya Kullanıcı Adı', 'pattern': r'\B@[\w_]{3,20}\b'},
        {'subcategory': 'Acil Durum İletişim Bilgisi', 'pattern': r'\bAcil Durum[:=]?\s?\d{10,11}\b'},
        {'subcategory': 'Vekalet Belgesi Sahibi Adı', 'pattern': r'\bVekil[:=]?\s?[A-ZÇĞİÖŞÜ][a-zçğıöşü]+\s[A-ZÇĞİÖŞÜ][a-zçğıöşü]+\b'},
        {'subcategory': 'Şirket Personel Sicil Numarası', 'pattern': r'\bSicil No[:=]?\s?\d{5,10}\b'},
        {'subcategory': 'Biyometrik Tanımlayıcı', 'pattern': r'\b(Biyometrik|Parmak İzi|Yüz Tanıma)[:=]?\s?[A-Z0-9_-]+\b'}
    ],
        'financialData': [
        {'subcategory': 'IBAN (TR formatı)', 'pattern': r'\bTR\d{2}\s?\d{5}\s?\d{1,16}\b'},
        {'subcategory': 'IBAN (Uluslararası – ISO 13616)', 'pattern': r'\b[A-Z]{2}\d{2}[A-Z0-9]{1,30}\b'},
        {'subcategory': 'Kredi Kartı Numarası (Visa)', 'pattern': r'\b4[0-9]{12}(?:[0-9]{3})?\b'},
        {'subcategory': 'Kredi Kartı Numarası (MasterCard)', 'pattern': r'\b5[1-5][0-9]{14}\b'},
        {'subcategory': 'Kredi Kartı Numarası (American Express)', 'pattern': r'\b3[47][0-9]{13}\b'},
        {'subcategory': 'Kredi Kartı CVV / CVC', 'pattern': r'\b[0-9]{3,4}\b'},
        {'subcategory': 'Kredi Kartı Son Kullanma Tarihi (MM/YY)', 'pattern': r'\b(0[1-9]|1[0-2])\/\d{2}\b'},
        {'subcategory': 'Kredi Kartı Sahibi Adı', 'pattern': r'\b[A-Z][a-z]+\s[A-Z][a-z]+\b'},
        {'subcategory': 'Banka Hesap Numarası (TR – 11 haneli)', 'pattern': r'\b\d{11}\b'},
        {'subcategory': 'Banka Müşteri Numarası', 'pattern': r'\b\d{7,12}\b'},
        {'subcategory': 'SWIFT / BIC Kodları', 'pattern': r'\b[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?\b'},
        {'subcategory': 'EFT Kodları (TR formatı)', 'pattern': r'\b\d{4,5}\b'},
        {'subcategory': 'POS Slip Üzerindeki Kart Bilgisi', 'pattern': r'\*{4}\s?\*{4}\s?\*{4}\s?\d{4}'},
        {'subcategory': 'Fatura Üzerindeki Kart Parçası', 'pattern': r'\*{4}\s?\*{4}\s?\*{4}\s?\d{4}'},
        {'subcategory': 'Banka Dekontundaki IBAN', 'pattern': r'\bTR\d{2}\s?\d{5}\s?\d{1,16}\b'},
        {'subcategory': 'Banka Dekontundaki Hesap Sahibi Adı', 'pattern': r'\b[A-Z][a-z]+\s[A-Z][a-z]+\b'},
        {'subcategory': 'Sanal Kart Bilgileri', 'pattern': r'\b\d{16}\b'},
        {'subcategory': 'Ödeme QR Kod İçeriği', 'pattern': r'(?i)QR\w{10,}'},
        {'subcategory': 'Kripto Cüzdan Adresi (BTC)', 'pattern': r'\b[13][a-km-zA-HJ-NP-Z1-9]{25,34}\b'},
        {'subcategory': 'Kripto Cüzdan Adresi (ETH)', 'pattern': r'0x[a-fA-F0-9]{40}'},
        {'subcategory': 'Kripto Transfer Hash', 'pattern': r'\b[a-f0-9]{64}\b'},
        {'subcategory': 'Vergi Levhası Üzerindeki TCKN / VKN', 'pattern': r'\b\d{10,11}\b'},
        {'subcategory': 'PayPal E-posta Hesabı', 'pattern': r'\b[a-zA-Z0-9._%+-]+@paypal.com\b'},
        {'subcategory': 'Ödeme Sistemi API Key', 'pattern': r'\b(sk_live|pk_live|access)_\w{20,40}\b'},
        {'subcategory': 'Finansal Rapor İçindeki Gelir-Gider Bilgisi', 'pattern': r'\bGelir:\s?\d+,\d{2}\s?₺|Gider:\s?\d+,\d{2}\s?₺\b'},
        {'subcategory': 'E-Fatura Belgesi Üzerindeki Vergi Bilgileri', 'pattern': r'\b\d{10,11}\b'},
        {'subcategory': 'Banka Müşteri Şifre (maskelenmemiş)', 'pattern': r'\b[A-Za-z0-9!@#$%^&*()_+=-\]{8,}\b'},
        {'subcategory': 'Borsa Hesap Kodu', 'pattern': r'\b[A-Z]{3}\d{4,6}\b'},
        {'subcategory': 'Kira Sözleşmesi Üzerindeki IBAN', 'pattern': r'\bTR\d{2}\s?\d{5}\s?\d{1,16}\b'},
        {'subcategory': 'E-Ticaret Sipariş Fişi Üzerindeki Kart Bilgisi', 'pattern': r'\*{4}\s?\*{4}\s?\*{4}\s?\d{4}'},
        {'subcategory': 'Alacak-verecek tablolarındaki ad-soyad eşleşmeleri', 'pattern': r'\b[A-Z][a-z]+\s[A-Z][a-z]+\b'},
        {'subcategory': 'SGK Ödeme Bildirgeleri', 'pattern': r'\bSGK\b.*\d{10,11}'},
        {'subcategory': 'Sigorta Poliçe Numarası', 'pattern': r'\b[A-Z]{2}\d{6,10}\b'},
        {'subcategory': 'Ödeme Onay SMS içeriği', 'pattern': r'\bOnay\sKodu[:\s]\d{4,6}\b'},
        {'subcategory': 'Mobil Bankacılık Giriş Logları', 'pattern': r'\bLogin\sfrom\sIP:\s(\d{1,3}\.){3}\d{1,3}\b'},
        {'subcategory': 'E-cüzdan Kullanıcı ID', 'pattern': r'\buser_[a-zA-Z0-9]{6,12}\b'},
        {'subcategory': 'POS Cihazına Bağlı İşlem Kaydı', 'pattern': r'\bPOS\sID:\s\d{6,10}\b'},
        {'subcategory': 'Banka Kredi Başvuru Formu Bilgileri', 'pattern': r'\bBaşvuru\sNo:\s\d{6,10}\b'},
        {'subcategory': 'Online Fatura Platformu Hesapları', 'pattern': r'\b[a-zA-Z0-9._%+-]+@.*\.com\b'},
        {'subcategory': 'Blockchain Cüzdan Logları', 'pattern': r'\bTxID:\s[a-fA-F0-9]{64}\b'}
    ],
    'healthData': [
        {'subcategory': 'T.C. Sağlık Bakanlığı Hasta Protokol Numarası', 'pattern': r'\bHPN-\d{6,10}\b'},
        {'subcategory': 'E-Nabız Hasta Kodu', 'pattern': r'\bEN\d{8,10}\b'},
        {'subcategory': 'Reçete Numarası', 'pattern': r'\bR[0-9]{10,12}\b'},
        {'subcategory': 'İlaç Barkod Numarası', 'pattern': r'\b(01)\d{14}(21)\d{6,20}\b'},
        {'subcategory': 'ICD-10 Hastalık Kodları', 'pattern': r'\b[A-TV-Z][0-9]{2}(\.[0-9]{1,2})?\b'},
        {'subcategory': 'Hasta Dosya Numarası', 'pattern': r'\bHDN-\d{6,10}\b'},
        {'subcategory': 'Kan Grubu Bilgisi', 'pattern': r'\b(A|B|AB|O)[+-]\b'},
        {'subcategory': 'Aşı Kartı Bilgileri', 'pattern': r'\bAŞI-[A-Z]{2,5}-\d{6,8}\b'},
        {'subcategory': 'Tahlil Sonuçları (glukoz, kolesterol vs.)', 'pattern': r'\b(Glukoz|Kolesterol|HbA1c|CRP)\s*[:=]?\s*\d{1,3}(\.\d{1,2})?\s*(mg/dL|g/dL|mmol/L)?\b'},
        {'subcategory': 'Laboratuvar Test Kodları', 'pattern': r'\b(LAB|TEST)-[A-Z0-9]{4,10}\b'}
    ],
    'corporateData': [
        {'subcategory': 'Vergi Kimlik Numarası (VKN)', 'pattern': r'\b[1-9]\d{9}\b'},
        {'subcategory': 'Ticaret Sicil Numarası', 'pattern': r'\b\d{6,10}\/?\d{4}\b'},
        {'subcategory': 'MERSİS Numarası', 'pattern': r'\b\d{16}\b'},
        {'subcategory': 'Şirket İmza Sirküsü Bilgileri', 'pattern': r'(?i)\b(imza sirkü|sirküsü|yetkili kişi|yetkilidir)\b'},
        {'subcategory': 'Fatura Numarası', 'pattern': r'\bFT-\d{6,10}\b|\bFAT\d{6,10}\b'},
        {'subcategory': 'İrsaliye Numarası', 'pattern': r'\bIR-\d{6,10}\b'},
        {'subcategory': 'Teklif Numarası / Kodları', 'pattern': r'\bTEK-\d{5,10}\b'},
        {'subcategory': 'Sözleşme Referans Numaraları', 'pattern': r'\bSÖZ-\d{5,10}\b|\bCONTR-\d{6,10}\b'},
        {'subcategory': 'Şirket Banka IBAN Bilgisi', 'pattern': r'\bTR\d{2}\s?\d{4}\s?\d{4}\s?\d{4}\s?\d{4}\s?\d{2}\b'},
        {'subcategory': 'Şirket Kredi Kartı Bilgisi', 'pattern': r'(?:\d{4}[- ]?){3}\d{4}'},
        {'subcategory': 'SWIFT / BIC Kodları', 'pattern': r'\b[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?\b'},
        {'subcategory': 'Kurumsal e-posta adresleri', 'pattern': r'\b[A-Za-z0-9._%+-]+@(?:[A-Za-z0-9-]+\.)+(com|com\.tr|org|biz|gov|edu|net)\b'},
        {'subcategory': 'Şirket Sunucu IP adresleri', 'pattern': r'\b(?:\d{1,3}\.){3}\d{1,3}\b'},
        {'subcategory': 'Hosting Panel Kullanıcıları', 'pattern': r'(?i)\bcpanel|plesk|admin|root\b'},
        {'subcategory': 'Yıllık Ciro / Bilanço Verileri', 'pattern': r'\b\d{1,3}(\.\d{3})*,\d{2}\s?(TL|₺|TRY|USD|EUR)\b'},
        {'subcategory': 'Fatura PDF içerikleri', 'pattern': r'(?i)Fatura\sNo[:\s]?\d+|Vergi\sDairesi|Toplam\sTutar'},
        {'subcategory': 'KEP Adresi', 'pattern': r'\b[A-Za-z0-9._%+-]+@hs[0-9]*\.kep\.tr\b'},
        {'subcategory': 'Resmi Kurum Yazışma Referans Numaraları', 'pattern': r'\b\d{6,10}-[A-Z]{2,5}-\d{2,4}\b'},
        {'subcategory': 'Tedarikçi ID / Müşteri ID', 'pattern': r'\bTID-\d{5,10}\b|\bMID-\d{5,10}\b'},
        {'subcategory': 'Personel Bordro Kayıtları', 'pattern': r'(?i)\bBordro\sNo[:\s]?\d{4,10}\b'},
        {'subcategory': 'Ticari Sır İçeren Dosya Adları', 'pattern': r'(?i)(ticari_sir|gizli|confidential)[\w\-]*\.(docx?|xlsx?|pdf|txt)'},
        {'subcategory': 'E-Arşiv Fatura XML İçeriği', 'pattern': r'(?i)<InvoiceNumber>\d+</InvoiceNumber>'},
        {'subcategory': 'Ödeme Talimatı ID\'leri', 'pattern': r'\bÖD-\d{6,10}\b'},
        {'subcategory': 'Cari Hesap Kodu', 'pattern': r'\bCA\d{5,10}\b'},
        {'subcategory': 'ERP Sisteminden Çıkan Finansal Loglar', 'pattern': r'(?i)\bERP_LOG_[\w\d]{6,}\b'},
        {'subcategory': 'Kredi Risk Raporu Referansları', 'pattern': r'(?i)\bKRR-\d{6,10}\b'},
        {'subcategory': 'SMMM Onaylı Belgeler (PDF içerikleri)', 'pattern': r'(?i)SMMM\sOnayı|Serbest\sMuhasebeci|Mali\sMüşavir'},
        {'subcategory': 'Satış / Sipariş Takip Numaraları', 'pattern': r'\bSIP-\d{6,10}\b|\bSAT-\d{6,10}\b'},
        {'subcategory': 'Şirket İçin Tahsilat Makbuzları', 'pattern': r'(?i)\bMakbuz\sNo[:\s]?\d{6,}\b'},
        {'subcategory': 'GİB e-Fatura UUID', 'pattern': r'\b[0-9a-f]{32}\b'},
        {'subcategory': 'İhale Evrakları (ek dosya adlarında)', 'pattern': r'(?i)ihale(_|\s)?evrak(lar[ıi])?\.(pdf|docx|xlsx)'},
        {'subcategory': 'Resmi Kurum Yazışma Başlıkları ve Kodları', 'pattern': r'(?i)(T.C.|Resmi\sYazı|Yazı\sNo[:\s]?)\d+'},
        {'subcategory': 'Şirket Arşiv Dosya Kodları', 'pattern': r'\bARCH-[A-Z]{2,5}-\d{3,5}\b'},
        {'subcategory': 'Mali Mühür ID Bilgileri', 'pattern': r'\bMMID-\d{5,10}\b'},
        {'subcategory': 'Banka Hesap Özetleri (xlsx, csv)', 'pattern': r'(?i)hesap_ozeti.*\.(xlsx|csv)'},
        {'subcategory': 'Şirket Sicil Gazetesi Referansları', 'pattern': r'(?i)Ticaret\sSicil\sGazetesi.*\d{4,}'},
        {'subcategory': 'Yurt Dışı Gümrük Kodları', 'pattern': r'\bHS\d{6}\b|\bGTIP\s?\d{6,10}\b'},
        {'subcategory': 'Elektronik Tebligat Numarası', 'pattern': r'\bETN-\d{6,10}\b'},
        {'subcategory': 'Şirket Yetkilisi İmza Görselleri', 'pattern': r'(?i)(imza|yetkili).*?\.(png|jpg|jpeg|svg|webp)'},
        {'subcategory': 'Kredi Sözleşmesi Numarası', 'pattern': r'\bKSN-\d{6,10}\b'}
    ],
    'locationData': [
        {'subcategory': 'IPv4 Adresi', 'pattern': r'\b(?:\d{1,3}\.){3}\d{1,3}\b'},
        {'subcategory': 'IPv6 Adresi', 'pattern': r'\b(?:[A-Fa-f0-9]{1,4}:){7}[A-Fa-f0-9]{1,4}\b'},
        {'subcategory': 'MAC Adresi', 'pattern': r'\b(?:[0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}\b'},
        {'subcategory': 'GPS Koordinatları', 'pattern': r'[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),\s*[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)'},
        {'subcategory': 'Adres Satırı (TR)', 'pattern': r'(?i)\b(?:mahalle|cadde|sokak|apt|blok|no\.?|kat|daire)\b.*'},
        {'subcategory': 'Ülke – İl – İlçe (TR)', 'pattern': r'\b(?:İstanbul|Ankara|İzmir|Adana|Konya|Gaziantep|Türkiye|TR)\b'},
        {'subcategory': 'Posta Kodu (TR)', 'pattern': r'\b\d{5}\b'},
        {'subcategory': 'CIDR IP Aralığı', 'pattern': r'\b(?:\d{1,3}\.){3}\d{1,3}/\d{1,2}\b'},
        {'subcategory': 'Google Maps Linki', 'pattern': r'https?:\/\/(www\.)?google\.[a-z.]+\/maps[^\s]+'},
        {'subcategory': 'IP + Lokasyon Eşleşmesi', 'pattern': r'\b(?:\d{1,3}\.){3}\d{1,3}\b.*?\b(?:İstanbul|Ankara|TR|Europe|Asia)\b'},
        {'subcategory': 'Mobil Uygulama GPS Verisi', 'pattern': r'"location":\s*{\s*"lat":\s*-?\d+\.\d+,\s*"lng":\s*-?\d+\.\d+'},
        {'subcategory': 'GeoIP JSON Çıktısı', 'pattern': r'"ip":\s*"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}",.*"country":\s*".*?"'},
        {'subcategory': 'Mobil Ağ Bilgileri', 'pattern': r'\bMCC:\s*\d+\s*MNC:\s*\d+\s*LAC:\s*\d+\s*CID:\s*\d+'},
        {'subcategory': 'Wi-Fi SSID / BSSID', 'pattern': r'(?:SSID|BSSID):\s*[\w-]+'},
        {'subcategory': 'IP\'den Lokasyon Bilgisi', 'pattern': r'\b\d{1,3}(?:\.\d{1,3}){3}\b.*?(City|Country|Region):\s*[\w\s]+'},
        {'subcategory': 'Wi-Fi Access Point Listesi', 'pattern': r'"ssid":\s*".*?",\s*"bssid":\s*"[0-9a-fA-F:]{17}"'},
        {'subcategory': 'Tarayıcıdan Alınan Konum', 'pattern': r'navigator\.geolocation\.getCurrentPosition'},
        {'subcategory': 'Navigasyon Rota Logları', 'pattern': r'(\[\s*-?\d+\.\d+,\s*-?\d+\.\d+\s*\],?\s*)+'},
        {'subcategory': 'Teslimat/Taksi GPS Noktaları', 'pattern': r'"delivery_location":\s*\[\s*-?\d+\.\d+,\s*-?\d+\.\d+\s*\]'},
        {'subcategory': 'Drone Loglarında GPS', 'pattern': r'GPS:\s*Lat:\s*-?\d+\.\d+,\s*Lon:\s*-?\d+\.\d+'},
        {'subcategory': 'Sosyal Medya Gönderisi Konum Verisi', 'pattern': r'"location":\s*{.*?"name":\s*".*?"'},
        {'subcategory': 'EXIF GPS Etiketleri', 'pattern': r'GPSLatitude.*?GPSLongitude.*?'},
        {'subcategory': 'Harita URL Parametreleri', 'pattern': r'[\?&]lat=-?\d+\.\d+&lng=-?\d+\.\d+'},
        {'subcategory': 'QR Kod İçinde Konum', 'pattern': r'geo:-?\d+(\.\d+)?,-?\d+(\.\d+)?'},
        {'subcategory': 'WebRTC IP Leak', 'pattern': r'candidate:\d+\s+\d+\s+udp\s+\d+\s+[\d\.]+'},
        {'subcategory': 'IoT Lokasyon Verisi', 'pattern': r'"device_location":\s*{\s*"lat":\s*-?\d+\.\d+,\s*"lon":\s*-?\d+\.\d+'},
        {'subcategory': 'Araç Konum Logları', 'pattern': r'VehicleLocation:\s*\[\s*-?\d+\.\d+,\s*-?\d+\.\d+\s*\]'},
        {'subcategory': 'Drone GPS Takibi', 'pattern': r'"drone_gps":\s*\[\s*-?\d+\.\d+,\s*-?\d+\.\d+\s*\]'},
        {'subcategory': 'Lokasyon Tabanlı Bildirim Logları', 'pattern': r'location_triggered":\s*true,\s*"coordinates":\s*\[.*?\]'},
        {'subcategory': 'Coğrafi Etiketli JSON', 'pattern': r'"geo":\s*{\s*"lat":.*?,\s*"lon":.*?}'},
        {'subcategory': 'Uygulama içi last_known_location', 'pattern': r'"last_known_location":\s*\[.*?\]'},
        {'subcategory': 'Rapor İçinde Adres/Koordinat Blokları', 'pattern': r'Adres[:]?[\s\S]{5,80}(Sokak|Mahalle|Cadde|No|Kat)'},
        {'subcategory': 'Haritada Kullanıcı İşaretleme', 'pattern': r'"map_marker":\s*{\s*"title":\s*".*?",\s*"location":\s*\[.*?\]'},
        {'subcategory': 'IP → Location eşlemesi', 'pattern': r'IP:\s*\d{1,3}(?:\.\d{1,3}){3}\s+Location:\s+\w+'},
        {'subcategory': 'Indoor Navigation Logları', 'pattern': r'building_id.*?floor.*?lat.*?lon'},
        {'subcategory': 'Zaman + Adres eşleşmeleri', 'pattern': r'(\d{2}:\d{2}|\d{2}/\d{2}/\d{4}).*?(Sokak|Cadde|Mahalle)'},
        {'subcategory': 'Teslimat Noktası / Pickup Adresi', 'pattern': r'"pickup_address":\s*".*?(Mahalle|Sokak|No)"'},
        {'subcategory': 'IP Tabanlı Kısıtlama', 'pattern': r'Access denied for IP \d{1,3}(?:\.\d{1,3}){3} from country .*?'},
        {'subcategory': 'E-ticaret Fatura Adres Blokları', 'pattern': r'"billing_address":\s*".*?(Mahalle|Cadde|No)"'},
        {'subcategory': 'Baz İstasyonu Bağlantı Geçmişi', 'pattern': r'ConnectedCell:\s*CellID:\s*\d+,\s*LAC:\s*\d+'}
    ],
    'authData': [
        {'subcategory': 'Kullanıcı Adı', 'pattern': r'(?i)(username|user_?id|kullanici_?adi)[\s:=]+["\']?[a-zA-Z0-9_.-]+["\']?'},
        {'subcategory': 'Parola', 'pattern': r'(?i)(password|sifre|pwd|pass)[\s:=]+["\']?.{4,}["\']?'},
        {'subcategory': 'Maskelenmiş Parola', 'pattern': r'\*{4,}'},
        {'subcategory': 'Base64 Şifreli Metin', 'pattern': r'(?:[A-Za-z0-9+/]{4}){2,}(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?'},
        {'subcategory': 'MD5 Hash', 'pattern': r'\b[a-fA-F0-9]{32}\b'},
        {'subcategory': 'SHA256 Hash', 'pattern': r'\b[a-fA-F0-9]{64}\b'},
        {'subcategory': 'OAuth / Bearer Token', 'pattern': r'Bearer\s+[A-Za-z0-9\-_.]+'},
        {'subcategory': 'API Key', 'pattern': r'(?i)(api[_-]?key|secret|token)[\s:=]+["\']?[A-Za-z0-9\-_=]{20,}["\']?'},
        {'subcategory': 'Session ID / Cookie', 'pattern': r'(sessionid|jsessionid|phpsessid)=([a-zA-Z0-9]+)'},
        {'subcategory': 'Email ve Şifre Kombinasyonu', 'pattern': r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+\s*[:=]\s*.{4,}'},
        {'subcategory': 'SSH Private Key', 'pattern': r'-----BEGIN (RSA|OPENSSH) PRIVATE KEY-----'},
        {'subcategory': 'SSH Public Key', 'pattern': r'ssh-(rsa|ed25519)\s+[A-Za-z0-9+/=]+'},
        {'subcategory': '.env Dosyası Login Bilgileri', 'pattern': r'(?i)(DB_USERNAME|DB_PASSWORD|LOGIN_USER|AUTH_TOKEN)=["\']?.+[\"\']?'},
        {'subcategory': 'FTP Kullanıcı Bilgileri', 'pattern': r'ftp:\/\/[a-zA-Z0-9]+:[^@]+@[^\/]+'},
        {'subcategory': 'AWS Access Key', 'pattern': r'AKIA[0-9A-Z]{16}'},
        {'subcategory': 'AWS Secret Key', 'pattern': r'(?i)aws_secret_access_key\s*=\s*[A-Za-z0-9\/+=]{40}'},
        {'subcategory': 'Google Service Account Key', 'pattern': r'"private_key":\s*"-----BEGIN PRIVATE KEY-----[\s\S]+?-----END PRIVATE KEY-----"'},
        {'subcategory': 'Database Kullanıcı Adı / Şifre', 'pattern': r'(?i)(db_user|db_pass|mysql_user|postgres_pass)[\s:=]+["\']?.+[\"\']?'},
        {'subcategory': 'GitHub Token', 'pattern': r'ghp_[A-Za-z0-9]{36}'},
        {'subcategory': '.htpasswd', 'pattern': r'[a-zA-Z0-9_-]+:\$[0-9]\$.+'},
        {'subcategory': 'SAML Assertion Token', 'pattern': r'<Assertion[^>]*>[\s\S]*?<\/Assertion>'},
        {'subcategory': 'JWT Token', 'pattern': r'[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+'},
        {'subcategory': 'Cookie Anahtarları', 'pattern': r'PHPSESSID=[a-zA-Z0-9]{26,}'},
        {'subcategory': 'LDAP Bind Pattern', 'pattern': r'ldap:\/\/[^:]+:[^@]+@[^\/]+'}
    ],
    'educationData': [
        {'subcategory': 'Okul / Üniversite Adı', 'pattern': r'\b(Üniversitesi|Fakültesi|Lisesi|İlkokulu|Ortaokulu|Enstitüsü|Meslek Yüksekokulu|Vocational School|University|College|Faculty|Institute)\b'},
        {'subcategory': 'Mezuniyet Yılı', 'pattern': r'\b(19[5-9][0-9]|20[0-4][0-9]|2050)\b'},
        {'subcategory': 'Öğrenci Numarası', 'pattern': r'\b\d{7,12}\b'},
        {'subcategory': 'Diploma Numarası', 'pattern': r'\b[Dd][Ii][Pp][Nn][Oo][: ]*\d{6,12}\b'},
        {'subcategory': 'Transkript Belgesi ID', 'pattern': r'\b[Tt][Rr][Aa][Nn][Ss][Cc][Rr][Ii][Pp][Tt][_ -]?\d{5,10}\b'},
        {'subcategory': 'Öğrenci Belgesi Formatı', 'pattern': r'\bÖğrenci Belgesi\b.*?(PDF|.pdf|Belgesi No[: ]*\d+)'},
        {'subcategory': 'Akademik Derece', 'pattern': r'\b(Lisans|Yüksek Lisans|Doktora|Ph\.?D|Bachelor\'?s|Master\'?s|Doctorate)\b'},
        {'subcategory': 'Bölüm / Anabilim Dalı', 'pattern': r'\b(Bilgisayar|Elektrik|Makine|İnşaat|Endüstri|Tıp|Hukuk|İktisat|İşletme|Psikoloji|Sosyoloji|Uluslararası|Matematik|Fizik|Kimya|Biyoloji)\b'},
        {'subcategory': 'Öğrenim Türü', 'pattern': r'\b(İkinci Öğretim|İÖ|Uzaktan Eğitim|Tam Zamanlı|Yarı Zamanlı)\b'},
        {'subcategory': 'Not Ortalaması (GPA)', 'pattern': r'\b(Ortalama|GPA)[: ]*(\d{1,2}\.\d{1,2}|\d{1,2})\b'},
        {'subcategory': 'Mezuniyet Belgesi Tarama Kaydı', 'pattern': r'\b(Mezuniyet Belgesi|Diploma)[:\s]*No[:\s]*\d{5,12}'},
        {'subcategory': 'Eğitim Sertifikası', 'pattern': r'\b(Coursera|Udemy|Khan Academy|edX|LinkedIn Learning).*(Certificate|Sertifika)'},
        {'subcategory': 'Sertifika ID / Doğrulama Linki', 'pattern': r'\b(Certificate ID|Sertifika No)[:\s]*[A-Z0-9-]{6,}'},
        {'subcategory': 'Eğitim Süresi', 'pattern': r'\b(20\d{2})[-–](20\d{2})\b'},
        {'subcategory': 'Eğitim Kurumları e-posta', 'pattern': r'\b[\w\.-]+@[\w\.-]+\.edu(\.tr|\.com|\.org)\b'},
        {'subcategory': 'Online Kurs Platform Sertifikaları', 'pattern': r'\b(Coursera|Udemy|edX|Khan Academy).*(Certificate|Sertifika|Completion)'},
        {'subcategory': 'Katılım Belgeleri', 'pattern': r'\b(Katılım Belgesi|Participation Certificate).*(\.pdf|\.jpg|\.jpeg|\.png)\b'},
        {'subcategory': 'Ders İçerikleri', 'pattern': r'\b(Ders|Course|Akademik Plan).*(İçeriği|Planı|Syllabus)\b'},
        {'subcategory': 'Staj Belgeleri', 'pattern': r'\b(Staj Belgesi|Internship Certificate|İşyeri Belgesi)\b'},
        {'subcategory': 'Erasmus / Exchange Belge Numaraları', 'pattern': r'\b(Erasmus|Exchange).*(Belge|Document)[\s:-]*\d{4,10}'},
        {'subcategory': 'İngilizce Hazırlık Belgesi', 'pattern': r'\b(İngilizce Hazırlık|English Prep).*(Belge|Certificate)\b'},
        {'subcategory': 'Uluslararası Sınav Sonuçları', 'pattern': r'\b(IELTS|TOEFL|SAT|GRE|GMAT)[\s:]*\d{1,3}(\.\d{1,2})?\b'},
        {'subcategory': 'Öğretmen Sicil Numarası', 'pattern': r'\b(Sicil No|Öğretmen Numarası)[:\s]*\d{6,10}\b'},
        {'subcategory': 'Öğrenci Kart Numarası', 'pattern': r'\b(Kart No|Student Card)[:\s]*\d{5,12}\b'},
        {'subcategory': 'Üniversite Kütüphane Hesap Numarası', 'pattern': r'\b(Kütüphane Hesabı|Library Account)[\s:]*\d{5,10}\b'},
        {'subcategory': 'Öğrenci Sistemi Giriş Bilgileri', 'pattern': r'\b(Student Portal|OBS|Öğrenci Bilgi Sistemi).*(Kullanıcı|Şifre|User|Password)\b'},
        {'subcategory': 'Not Döküm Belgeleri', 'pattern': r'\b(Transkript|Not Dökümü|Transcript)\b'},
        {'subcategory': 'Mezuniyet Töreni Katılım Belgeleri', 'pattern': r'\b(Mezuniyet Töreni|Graduation Ceremony).*(Belgesi|Certificate)\b'},
        {'subcategory': 'Üniversiteye Giriş Yılı / Dönemi', 'pattern': r'\b(Giriş Yılı|Entry Year|Dönem|Semester)[:\s]*20\d{2}\b'},
        {'subcategory': 'Fakülte / Enstitü Etiketleri', 'pattern': r'\b(Fakülte|Fak.|Enstitü|Enst.)[\s\w]{2,50}\b'},
        {'subcategory': 'Açık Öğretim Bilgileri', 'pattern': r'\b(Açık Öğretim|AÖF|AUZEF|ATA-AÖF|AOF-Final)[\w\s\-]*\b'},
        {'subcategory': 'ÖSYM Sınav Sonuç Belgeleri', 'pattern': r'\b(ÖSYM|Sınav Sonuç|Sonuç Belgesi|Exam Result)[\s\w\-]*\b'},
        {'subcategory': 'KPSS, ALES, YÖKDİL gibi sınav belgeleri', 'pattern': r'\b(KPSS|ALES|YÖKDİL|YDS|YÖK|e-YDS)[\s\w\-]*\b'},
        {'subcategory': 'Ulusal sertifikasyonlar', 'pattern': r'\b(MEB|TSE|TÜRKAK)[\s\-]*(Sertifika|Belge|Onay)\b'},
        {'subcategory': 'Eğitimle ilişkilendirilmiş QR kodlar', 'pattern': r'\b(QR[\s\-]?Kod).*(Eğitim|Sertifika|Belge)\b'},
        {'subcategory': 'Akademik Referanslar', 'pattern': r'\b(Referans|Öneri Mektubu|Recommendation Letter|Academic Ref)\b'},
        {'subcategory': 'E-devlet\'ten alınan diplomalar', 'pattern': r'\b(E-Devlet).*(Diploma|Belge|Sorgu|PDF)\b'},
        {'subcategory': 'Mezun Takip Sistemleri', 'pattern': r'\b(Mezun Takip|Alumni Tracking|Mezun Bilgi Sistemi)\b'},
        {'subcategory': 'Sertifika doğrulama API sonuçları', 'pattern': r'\b(Sertifika|Certificate)[\s\-]*(Doğrula|Validate|Verification)[\s\-]*(Link|API|URL)?\b'},
        {'subcategory': 'Öğrenci transkriptinde yer alan ders listeleri', 'pattern': r'\b(Ders|Course)[\s\-]*(Kodu|Adı|Name|Code)[:\s]*[A-Z]{2,4}[-\s]?\d{3}\b'}
    ],
    'systemSecurityData': [
        {'subcategory': 'Şifre Değişim Kayıtları', 'pattern': r'\b(password\s+(changed|reset|updated)|passwd\s+-[a-z]*\s+[a-z]+)\b'},
        {'subcategory': 'Dosya Erişim Kayıtları', 'pattern': r'\b(open|read|write|access)\s+(file|/[\w/\.]+)\b'},
        {'subcategory': 'Sunucu Hata Raporları', 'pattern': r'\b(server\s+(error|fail|crash)|500\s+Internal\s+Server\s+Error)\b'},
        {'subcategory': 'Erişim Kontrol Listeleri (ACL)', 'pattern': r'\b(acl\s+(grant|deny|allow)|access\s+list)\b'},
        {'subcategory': 'Kullanıcı İzin Değişikliği Logları', 'pattern': r'\b(permission\s+(granted|revoked|changed)|chmod\s+[0-7]{3,4})\b'},
        {'subcategory': 'Kullanıcı Rolleri ve İzin Logları', 'pattern': r'\b(role\s+(assigned|revoked)|group\s+add)\b'},
        {'subcategory': 'Şifre Kırma Çalışmaları (Brute Force)', 'pattern': r'\b(failed\s+login\s+attempts|brute\s+force\s+detected)\b'},
        {'subcategory': 'Güvenlik Duvarı Ayarları ve İzinler', 'pattern': r'\b(firewall\s+(allowed|blocked|rule\s+added)|iptables\s+-[A-Z]*)\b'},
        {'subcategory': 'Ağ Bağlantıları ve Port Erişim Kayıtları', 'pattern': r'\b(port\s+[0-9]+(\/tcp|\/udp)?\s+(opened|closed|listening))\b'},
        {'subcategory': 'Sistem Performans İstatistikleri', 'pattern': r'\b(cpu\s+usage|memory\s+usage|load\s+average)\b'},
        {'subcategory': 'Yöneticilerin Sistem Erişim Logları', 'pattern': r'\b(admin\s+login\s+from\s+\d{1,3}(\.\d{1,3}){3})\b'},
        {'subcategory': 'Güvenlik İhlalleri ve Yetki Aşımları', 'pattern': r'\b(unauthorized\s+access|privilege\s+escalation)\b'},
        {'subcategory': 'Çalışan Antivirus ve Malware Taramaları', 'pattern': r'\b(scan\s+started|malware\s+found|virus\s+detected)\b'},
        {'subcategory': 'Temizleme ve Karantina Kayıtları', 'pattern': r'\b(file\s+(quarantined|deleted|cleaned))\b'},
        {'subcategory': 'İzinsiz Erişim Denemeleri (Root, Sudo)', 'pattern': r'\b(sudo:\s+[\w]+\s+:(\s+)?(authentication\s+failure|not\s+allowed))\b'},
        {'subcategory': 'Veritabanı Yönetim Sistemleri Logları', 'pattern': r'\b(sql\s+(error|select|drop|alter)|db\s+connection\s+(fail|refused))\b'},
        {'subcategory': 'Bağlantı İzinleri ve IP Denetimleri', 'pattern': r'\b(whitelist|blacklist|ip\s+blocked|connection\s+denied)\b'},
        {'subcategory': 'Tarayıcı ve Uygulama Erişim Kayıtları', 'pattern': r'\b(user-agent|browser\s+access|GET\s+/[\w\-]*)\b'},
        {'subcategory': 'Şifreleme Anahtarları Erişim Logları', 'pattern': r'\b(private\s+key\s+accessed|certificate\s+loaded|ssl\s+error)\b'},
        {'subcategory': 'Sistem Denetim ve Görev Kayıtları', 'pattern': r'\b(audit\s+(log|trail|entry)|cron\s+(run|triggered))\b'},
        {'subcategory': 'Kullanıcı Giriş Bilgileri', 'pattern': r'\b(?:\d{1,3}\.\d{1,3}){3}\.\d{1,3}\b.*? (?:GET|POST|PUT|DELETE)'},
        {'subcategory': 'Zaman Damgası', 'pattern': r'\b(?:\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})\b'},
        {'subcategory': 'Erişim İzleri', 'pattern': r'login|logout|access granted|access denied'},
        {'subcategory': 'Yetkilendirme Logları', 'pattern': r'(authorized|unauthorized|privilege escalation)'},
        {'subcategory': 'Hatalı Giriş Denemeleri', 'pattern': r'(failed login|invalid password|incorrect credentials)'},
        {'subcategory': 'Sistem Hataları', 'pattern': r'error\s+\d{3}|exception|critical'},
        {'subcategory': 'Uygulama Logları', 'pattern': r'(app|application)\s+(started|stopped|crashed)'},
        {'subcategory': 'Veri Tabanı Sorgu Kayıtları', 'pattern': r'(SELECT|INSERT|UPDATE|DELETE)\s+.*?\s+FROM'},
        {'subcategory': 'Güncellemeler', 'pattern': r'(update|upgrade)\s+(installed|completed|failed)'},
        {'subcategory': 'Sunucu Hataları', 'pattern': r'(server error|500|503|connection refused)'},
        {'subcategory': 'Güvenlik Uyarıları', 'pattern': r'(firewall|IDS|IPS|alert|breach detected)'},
        {'subcategory': 'Şüpheli Aktivite', 'pattern': r'(suspicious|anomaly|unusual traffic)'},
        {'subcategory': 'Ağ Trafiği Logları', 'pattern': r'(TCP|UDP)\s+connection.*?\d{1,3}(?:\.\d{1,3}){3}'},
        {'subcategory': 'Yedekleme Kayıtları', 'pattern': r'(backup\s+(completed|failed)|restore\s+started)'},
        {'subcategory': 'Aktif Oturumlar', 'pattern': r'(session start|active session|login session)'},
        {'subcategory': 'Şifre Değişimi', 'pattern': r'(password change|pwd update)'},
        {'subcategory': 'Dosya Erişim Kayıtları', 'pattern': r'(file accessed|read|write|open|delete)'},
        {'subcategory': 'Erişim Kontrol Listeleri', 'pattern': r'(ACL|access list)'},
        {'subcategory': 'Kullanıcı İzin Değişikliği', 'pattern': r'(permission changed|user rights updated)'},
        {'subcategory': 'Roller ve İzinler', 'pattern': r'(role assigned|role revoked)'},
        {'subcategory': 'API Güvenlik Logları', 'pattern': r'(?i)\b(api(_key|secret)?|token)[\s:=]+["\']?[\w\-]{16,}["\']?'},
        {'subcategory': 'Sunucu Yük Dengeleme Logları', 'pattern': r'\b(load[_\s]?balancer|lb)-?(log|status)[\s:=]+.*'},
        {'subcategory': 'Uyumluluk Denetimi Kayıtları', 'pattern': r'\b(compliance|audit)[_\s]?(check|report|status)[\s:=]+.*'},
        {'subcategory': 'Güvenlik Duyuru ve Acil Durum Uyarıları', 'pattern': r'\b(security|alert|incident|emergency)[_\s]?(notification|message|warn)[\s:=]+.*'},
        {'subcategory': 'Web Sunucu ve Proxy Logları', 'pattern': r'\b(GET|POST|PUT|DELETE|HEAD)\s+/[\w\-\/\.]*\s+HTTP\/[0-9.]'},
        {'subcategory': 'E-posta ve İletişim Logları', 'pattern': r'\b(from|to|cc|bcc):\s*[\w\.-]+@[\w\.-]+\.\w{2,}'},
        {'subcategory': 'Veri Aktarımı ve Yedekleme İzleri', 'pattern': r'\b(backup|transfer|rsync|scp|ftp|tar)[_\s]?(log|status)?[:=]?[\s]*[\w\-\/\.]+'},
        {'subcategory': 'Sistem Uygulama Günlük Dosyaları', 'pattern': r'\/var\/log\/(syslog|journal|messages|kern\.log|auth\.log)'},
        {'subcategory': 'Sistem Koruma ve Güvenlik Düzeyleri', 'pattern': r'\b(selinux|apparmor|firewalld|ufw)[\s:=]+(enabled|enforcing|disabled)'},
        {'subcategory': 'Audit Logları', 'pattern': r'\baudit(?:d)?\.log\b|\baudit[_\s]?trail\b'},
        {'subcategory': 'Sistem İnceleme Raporları', 'pattern': r'\b(security|system)[_\s]?(audit|review|inspection)[_\s]?report\b'},
        {'subcategory': 'İzin Değişiklik ve Hata Tespiti', 'pattern': r'\bchmod|chown|setfacl|Permission\s+(denied|granted|changed)'},
        {'subcategory': 'Güvenlik Güncellemesi İzleme', 'pattern': r'\b(update|upgrade|patch)[_\s]?(security|log)?[\s:=]+.*'},
        {'subcategory': 'OS Koruma (SELinux, AppArmor) Logları', 'pattern': r'\b(SELinux|AppArmor)[\s:=]+(enforcing|complain|disabled)'},
        {'subcategory': 'Sunucu Erişim Kısıtlamaları', 'pattern': r'\b(whitelist|blacklist|blocklist|allowlist)[\s:=]+(\d{1,3}\.){3}\d{1,3}'},
        {'subcategory': 'Sistem Güvenlik Duvarı Logları', 'pattern': r'\biptables|firewalld|ufw|nftables\b.*(DROP|ACCEPT|REJECT)'},
        {'subcategory': 'Kullanıcı Uygulama Verisi ve Dosya İzin Kayıtları', 'pattern': r'\buser=.* file=.* permission=(read|write|execute|denied)'},
        {'subcategory': 'Anomalik Aktivite Tespit Raporları', 'pattern': r'\banomal(y|ies)?[_\s]?(detected|log|report)\b'},
        {'subcategory': 'DDoS ve Trafik Yükü Logları', 'pattern': r'\b(ddos|flood|rate[_\s]?limit|traffic spike)[_\s]?(alert|log)\b'},
        {'subcategory': 'Sistem Değişiklik ve Konfigürasyon Kayıtları', 'pattern': r'\b(config|configuration|settings|parameter)[_\s]?(change|update|modify)[\s:=]+'},
        {'subcategory': 'VPN ve Proxy Tünel İzleme', 'pattern': r'\b(vpn|proxy|tunnel)[_\s]?(connect|disconnect|log)\b'},
        {'subcategory': 'Log Toplama ve Dağıtım Sistemleri', 'pattern': r'\b(splunk|logstash|elasticsearch|kibana|graylog)[_\s]?(event|log|trace)?'},
        {'subcategory': 'Yedekleme Erişimi ve Durum Raporları', 'pattern': r'\bbackup[_\s]?(status|report|success|fail)\b'},
        {'subcategory': 'API Erişim Kayıtları', 'pattern': r'\b(api|rest)[_\s]?access[\s:=]+.*'},
        {'subcategory': 'Sistem Yük ve Performans İzlemeleri', 'pattern': r'\b(load average|cpu usage|memory usage)[\s:=]+.*'},
        {'subcategory': 'Hata Kodu Raporları ve Çözümleri', 'pattern': r'\b(error code|exception|fail|crash)[\s:=]+(40\d|50\d|\w+)'}
    ],
    'socialMediaData': [
        {'subcategory': 'Instagram Kullanıcı Adı', 'pattern': r'\b@[\w._]{1,30}\b'},
        {'subcategory': 'Twitter Kullanıcı Adı', 'pattern': r'\b@[\w_]{1,15}\b'},
        {'subcategory': 'Facebook Profil Linki', 'pattern': r'https?://(?:www\.)?facebook\.com/[\w\.-]+'},
        {'subcategory': 'LinkedIn Profil Linki', 'pattern': r'https?://(?:www\.)?linkedin\.com/in/[\w-]+'},
        {'subcategory': 'YouTube Kanal Linki', 'pattern': r'https?://(?:www\.)?youtube\.com/(?:c/|channel/|user/)[\w-]+'},
        {'subcategory': 'TikTok Kullanıcı Adı', 'pattern': r'\b@[\w._]{2,24}\b'},
        {'subcategory': 'Discord Kullanıcı Adı', 'pattern': r'[\w._]{2,32}#\d{4}'},
        {'subcategory': 'Reddit Kullanıcı Adı', 'pattern': r'\bu/[\w_-]{3,20}\b'},
        {'subcategory': 'Telegram Kullanıcı Adı', 'pattern': r'\b@[\w_]{5,32}\b'},
        {'subcategory': 'WhatsApp Grup Linki', 'pattern': r'https?://chat\.whatsapp\.com/[\w-]+'},
        {'subcategory': 'Medium Profil Linki', 'pattern': r'https?://medium\.com/@[\w-]+'},
        {'subcategory': 'GitHub Profil Linki', 'pattern': r'https?://github\.com/[\w-]+'},
        {'subcategory': 'Stack Overflow Profil Linki', 'pattern': r'https?://stackoverflow\.com/users/\d+/[\w-]+'},
        {'subcategory': 'Quora Profil Linki', 'pattern': r'https?://www\.quora\.com/profile/[\w-]+'},
        {'subcategory': 'Pinterest Profil Linki', 'pattern': r'https?://(?:www\.)?pinterest\.com/[\w-]+'},
        {'subcategory': 'Snapchat Kullanıcı Adı', 'pattern': r'\b[\w._-]{3,15}\b'},
        {'subcategory': 'Tumblr Blog Adı', 'pattern': r'https?://[\w-]+\.tumblr\.com'},
        {'subcategory': 'Vimeo Kullanıcı Linki', 'pattern': r'https?://vimeo\.com/[\w-]+'},
        {'subcategory': 'Behance Portfolyo Linki', 'pattern': r'https?://www\.behance\.net/[\w-]+'},
        {'subcategory': 'Dribbble Profil Linki', 'pattern': r'https?://dribbble\.com/[\w-]+'},
        {'subcategory': 'Flickr Profil Linki', 'pattern': r'https?://www\.flickr\.com/photos/[\w-]+'},
        {'subcategory': 'SoundCloud Profil Linki', 'pattern': r'https?://soundcloud\.com/[\w-]+'},
        {'subcategory': 'Spotify Profil Linki', 'pattern': r'https?://open\.spotify\.com/user/[\w-]+'},
        {'subcategory': 'Twitch Kullanıcı Adı', 'pattern': r'\b[\w_]{4,25}\b'},
        {'subcategory': 'Steam Profil Linki', 'pattern': r'https?://steamcommunity\.com/(?:id|profiles)/[\w-]+'},
        {'subcategory': 'DeviantArt Profil Linki', 'pattern': r'https?://[\w-]+\.deviantart\.com'},
        {'subcategory': 'Slack Workspace Linki', 'pattern': r'https?://[\w-]+\.slack\.com'},
        {'subcategory': 'Mastodon Profil Linki', 'pattern': r'https?://[\w-]+\.(?:mastodon|social)/@[\w-]+'},
        {'subcategory': 'Medium Yayın Linki', 'pattern': r'https?://medium\.com/[\w-]+/[\w-]+'},
        {'subcategory': 'Substack Bülten Linki', 'pattern': r'https?://[\w-]+\.substack\.com'},
        {'subcategory': 'Clubhouse Profil Linki', 'pattern': r'https?://www\.joinclubhouse\.com/@[\w-]+'},
        {'subcategory': 'OnlyFans Profil Linki', 'pattern': r'https?://onlyfans\.com/[\w-]+'},
        {'subcategory': 'Patreon Profil Linki', 'pattern': r'https?://www\.patreon\.com/[\w-]+'},
        {'subcategory': 'Kickstarter Proje Linki', 'pattern': r'https?://www\.kickstarter\.com/projects/[\w-]+'},
        {'subcategory': 'Indiegogo Proje Linki', 'pattern': r'https?://www\.indiegogo\.com/projects/[\w-]+'},
        {'subcategory': 'ProductHunt Profil Linki', 'pattern': r'https?://www\.producthunt\.com/@[\w-]+'},
        {'subcategory': 'AngelList Profil Linki', 'pattern': r'https?://angel\.co/[\w-]+'},
        {'subcategory': 'Crunchbase Profil Linki', 'pattern': r'https?://www\.crunchbase\.com/person/[\w-]+'},
        {'subcategory': 'SlideShare Profil Linki', 'pattern': r'https?://www\.slideshare\.net/[\w-]+'},
        {'subcategory': 'SpeakerDeck Profil Linki', 'pattern': r'https?://speakerdeck\.com/[\w-]+'},
        {'subcategory': 'Scribd Profil Linki', 'pattern': r'https?://www\.scribd\.com/user/[\w-]+'},
        {'subcategory': 'Issuu Profil Linki', 'pattern': r'https?://issuu\.com/[\w-]+'},
        {'subcategory': 'Academia.edu Profil Linki', 'pattern': r'https?://[\w-]+\.academia\.edu'},
        {'subcategory': 'ResearchGate Profil Linki', 'pattern': r'https?://www\.researchgate\.net/profile/[\w-]+'},
        {'subcategory': 'Google Scholar Profil Linki', 'pattern': r'https?://scholar\.google\.com/citations\?user=[\w-]+'},
        {'subcategory': 'ORCID ID', 'pattern': r'\b\d{4}-\d{4}-\d{4}-\d{4}\b'},
        {'subcategory': 'arXiv Profil Linki', 'pattern': r'https?://arxiv\.org/a/[\w-]+'},
        {'subcategory': 'SSRN Profil Linki', 'pattern': r'https?://papers\.ssrn\.com/sol3/cf_dev/AbsByAuth\.cfm\?per_id=[\w-]+'},
        {'subcategory': 'Mendeley Profil Linki', 'pattern': r'https?://www\.mendeley\.com/profiles/[\w-]+'},
        {'subcategory': 'Zotero Profil Linki', 'pattern': r'https?://www\.zotero\.org/[\w-]+'},
        {'subcategory': 'Figshare Profil Linki', 'pattern': r'https?://figshare\.com/authors/[\w-]+'},
        {'subcategory': 'Zenodo Profil Linki', 'pattern': r'https?://zenodo\.org/communities/[\w-]+'},
        {'subcategory': 'OSF Profil Linki', 'pattern': r'https?://osf\.io/[\w-]+'},
        {'subcategory': 'GitLab Profil Linki', 'pattern': r'https?://gitlab\.com/[\w-]+'},
        {'subcategory': 'Bitbucket Profil Linki', 'pattern': r'https?://bitbucket\.org/[\w-]+'},
        {'subcategory': 'SourceForge Profil Linki', 'pattern': r'https?://sourceforge\.net/u/[\w-]+'},
        {'subcategory': 'Launchpad Profil Linki', 'pattern': r'https?://launchpad\.net/~[\w-]+'},
        {'subcategory': 'CodePen Profil Linki', 'pattern': r'https?://codepen\.io/[\w-]+'},
        {'subcategory': 'JSFiddle Profil Linki', 'pattern': r'https?://jsfiddle\.net/user/[\w-]+'},
        {'subcategory': 'CodeSandbox Profil Linki', 'pattern': r'https?://codesandbox\.io/u/[\w-]+'},
        {'subcategory': 'Replit Profil Linki', 'pattern': r'https?://replit\.com/@[\w-]+'},
        {'subcategory': 'Glitch Profil Linki', 'pattern': r'https?://glitch\.com/@[\w-]+'},
        {'subcategory': 'StackBlitz Profil Linki', 'pattern': r'https?://stackblitz\.com/@[\w-]+'},
        {'subcategory': 'Codecademy Profil Linki', 'pattern': r'https?://www\.codecademy\.com/profiles/[\w-]+'},
        {'subcategory': 'LeetCode Profil Linki', 'pattern': r'https?://leetcode\.com/[\w-]+'},
        {'subcategory': 'HackerRank Profil Linki', 'pattern': r'https?://www\.hackerrank\.com/[\w-]+'},
        {'subcategory': 'Kaggle Profil Linki', 'pattern': r'https?://www\.kaggle\.com/[\w-]+'},
        {'subcategory': 'DataCamp Profil Linki', 'pattern': r'https?://www\.datacamp\.com/profile/[\w-]+'},
        {'subcategory': 'Udemy Profil Linki', 'pattern': r'https?://www\.udemy\.com/user/[\w-]+'},
        {'subcategory': 'Coursera Profil Linki', 'pattern': r'https?://www\.coursera\.org/user/[\w-]+'},
        {'subcategory': 'edX Profil Linki', 'pattern': r'https?://www\.edx\.org/user/[\w-]+'},
        {'subcategory': 'Skillshare Profil Linki', 'pattern': r'https?://www\.skillshare\.com/profile/[\w-]+'},
        {'subcategory': 'Pluralsight Profil Linki', 'pattern': r'https?://app\.pluralsight\.com/profile/[\w-]+'},
        {'subcategory': 'Treehouse Profil Linki', 'pattern': r'https?://teamtreehouse\.com/[\w-]+'},
        {'subcategory': 'Codecademy Pro Profil Linki', 'pattern': r'https?://www\.codecademy\.com/pro/[\w-]+'},
        {'subcategory': 'freeCodeCamp Profil Linki', 'pattern': r'https?://www\.freecodecamp\.org/[\w-]+'},
        {'subcategory': 'The Odin Project Profil Linki', 'pattern': r'https?://www\.theodinproject\.com/users/[\w-]+'},
        {'subcategory': 'Scrimba Profil Linki', 'pattern': r'https?://scrimba\.com/@[\w-]+'},
        {'subcategory': 'Frontend Mentor Profil Linki', 'pattern': r'https?://www\.frontendmentor\.io/profile/[\w-]+'},
        {'subcategory': 'Dev.to Profil Linki', 'pattern': r'https?://dev\.to/[\w-]+'},
        {'subcategory': 'Hashnode Profil Linki', 'pattern': r'https?://[\w-]+\.hashnode\.dev'},
        {'subcategory': 'Medium Yayın Linki', 'pattern': r'https?://medium\.com/[\w-]+/[\w-]+'},
        {'subcategory': 'Substack Bülten Linki', 'pattern': r'https?://[\w-]+\.substack\.com'},
        {'subcategory': 'Ghost Blog Linki', 'pattern': r'https?://[\w-]+\.ghost\.io'},
        {'subcategory': 'WordPress Blog Linki', 'pattern': r'https?://[\w-]+\.wordpress\.com'},
        {'subcategory': 'Blogspot Blog Linki', 'pattern': r'https?://[\w-]+\.blogspot\.com'},
        {'subcategory': 'Wix Blog Linki', 'pattern': r'https?://[\w-]+\.wixsite\.com'},
        {'subcategory': 'Squarespace Blog Linki', 'pattern': r'https?://[\w-]+\.squarespace\.com'},
        {'subcategory': 'Weebly Blog Linki', 'pattern': r'https?://[\w-]+\.weebly\.com'},
        {'subcategory': 'Tumblr Blog Linki', 'pattern': r'https?://[\w-]+\.tumblr\.com'},
        {'subcategory': 'LiveJournal Blog Linki', 'pattern': r'https?://[\w-]+\.livejournal\.com'},
        {'subcategory': 'Blogger Blog Linki', 'pattern': r'https?://[\w-]+\.blogspot\.com'},
        {'subcategory': 'TypePad Blog Linki', 'pattern': r'https?://[\w-]+\.typepad\.com'},
        {'subcategory': 'Posterous Blog Linki', 'pattern': r'https?://[\w-]+\.posterous\.com'},
        {'subcategory': 'Xanga Blog Linki', 'pattern': r'https?://[\w-]+\.xanga\.com'},
        {'subcategory': 'MySpace Profil Linki', 'pattern': r'https?://myspace\.com/[\w-]+'},
        {'subcategory': 'Friendster Profil Linki', 'pattern': r'https?://profiles\.friendster\.com/[\w-]+'},
        {'subcategory': 'Orkut Profil Linki', 'pattern': r'https?://www\.orkut\.com/[\w-]+'},
        {'subcategory': 'Hi5 Profil Linki', 'pattern': r'https?://hi5\.com/[\w-]+'},
        {'subcategory': 'Bebo Profil Linki', 'pattern': r'https?://www\.bebo\.com/[\w-]+'},
        {'subcategory': 'FriendFeed Profil Linki', 'pattern': r'https?://friendfeed\.com/[\w-]+'},
        {'subcategory': 'Delicious Profil Linki', 'pattern': r'https?://delicious\.com/[\w-]+'},
        {'subcategory': 'StumbleUpon Profil Linki', 'pattern': r'https?://www\.stumbleupon\.com/stumbler/[\w-]+'},
        {'subcategory': 'Digg Profil Linki', 'pattern': r'https?://digg\.com/@[\w-]+'},
        {'subcategory': 'Reddit Kullanıcı Adı', 'pattern': r'\bu/[\w_-]{3,20}\b'},
        {'subcategory': 'Reddit Subreddit', 'pattern': r'\br/[\w_-]{3,20}\b'},
        {'subcategory': 'Reddit Post Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/comments/[\w-]+'},
        {'subcategory': 'Reddit Comment Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/comments/[\w-]+/[\w-]+/[\w-]+'},
        {'subcategory': 'Reddit User Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/user/[\w-]+'},
        {'subcategory': 'Reddit Subreddit Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+'},
        {'subcategory': 'Reddit Wiki Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/wiki/[\w-]+'},
        {'subcategory': 'Reddit Modmail Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/message/moderator/[\w-]+'},
        {'subcategory': 'Reddit Modqueue Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/modqueue'},
        {'subcategory': 'Reddit Spam Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/spam'},
        {'subcategory': 'Reddit Reports Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/reports'},
        {'subcategory': 'Reddit Unmoderated Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/unmoderated'},
        {'subcategory': 'Reddit Edited Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/edited'},
        {'subcategory': 'Reddit Flair Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/flair'},
        {'subcategory': 'Reddit Rules Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/rules'},
        {'subcategory': 'Reddit Settings Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/settings'},
        {'subcategory': 'Reddit Traffic Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/traffic'},
        {'subcategory': 'Reddit Banned Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/banned'},
        {'subcategory': 'Reddit Muted Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/muted'},
        {'subcategory': 'Reddit Contributors Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/contributors'},
        {'subcategory': 'Reddit Moderators Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/moderators'},
        {'subcategory': 'Reddit Widgets Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/widgets'},
        {'subcategory': 'Reddit Stylesheet Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/stylesheet'},
        {'subcategory': 'Reddit Emojis Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/emojis'},
        {'subcategory': 'Reddit Post Requirements Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/post_requirements'},
        {'subcategory': 'Reddit Scheduled Posts Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/scheduled_posts'},
        {'subcategory': 'Reddit Post Drafts Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/post_drafts'},
        {'subcategory': 'Reddit Post Templates Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/post_templates'},
        {'subcategory': 'Reddit Post Flair Templates Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/post_flair_templates'},
        {'subcategory': 'Reddit User Flair Templates Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/user_flair_templates'},
        {'subcategory': 'Reddit Post Requirements Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/post_requirements'},
        {'subcategory': 'Reddit Scheduled Posts Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/scheduled_posts'},
        {'subcategory': 'Reddit Post Drafts Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/post_drafts'},
        {'subcategory': 'Reddit Post Templates Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/post_templates'},
        {'subcategory': 'Reddit Post Flair Templates Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/post_flair_templates'},
        {'subcategory': 'Reddit User Flair Templates Linki', 'pattern': r'https?://(?:www\.)?reddit\.com/r/[\w-]+/about/user_flair_templates'}
    ],
    'governmentData': [
        {'subcategory': 'T.C. Kimlik Numarası', 'pattern': r'\b[1-9]\d{10}[02468]\b'},
        {'subcategory': 'E-Devlet Şifresi (varsayımsal format)', 'pattern': r'\bE-Devlet\sŞifresi[:\\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu Personeli Sicil Numarası', 'pattern': r'\bKamu\sSicil\sNo[:\\s]?\d{8,12}\b'},
        {'subcategory': 'Seçmen Kayıt Numarası', 'pattern': r'\bSeçmen\sNo[:\\s]?\d{10,15}\b'},
        {'subcategory': 'Askerlik Durum Belgesi Referansı', 'pattern': r'\bAskerlik\sBelgesi[:\\s]?\d{5,10}\b'},
        {'subcategory': 'Adli Sicil Kaydı Referansı', 'pattern': r'\bAdli\sSicil[:\\s]?\d{5,10}\b'},
        {'subcategory': 'Pasaport Seri/Cüzdan No', 'pattern': r'\b([A-Z]\d{8}|\d{9})\b'},
        {'subcategory': 'Vize Başvuru Referans Numarası', 'pattern': r'\bVLN\d{8,12}\b'},
        {'subcategory': 'Kamu Kurumu Yazışma Numarası', 'pattern': r'\b[A-Z]{2,5}-\d{6,10}-[A-Z]{2,5}\b'},
        {'subcategory': 'Vergi Dairesi Kodu', 'pattern': r'\b\d{4,5}\b'},
        {'subcategory': 'E-Fatura/E-Arşiv GİB Referansı', 'pattern': r'\bTR[A-Z0-9]{16}\b'},
        {'subcategory': 'Gümrük Beyannamesi Referansı', 'pattern': r'\bGBN\d{10,15}\b'},
        {'subcategory': 'Tapu ve Kadastro Bilgileri (Örnek)', 'pattern': r'\b(Ada|Parsel)[:\s]?\d+\b'},
        {'subcategory': 'Nüfus Cüzdanı / Yeni Kimlik Seri No', 'pattern': r'\b[A-Z]{2}\d{6}\b'},
        {'subcategory': 'Evlenme / Boşanma Kayıt Referansı', 'pattern': r'\b(Evlenme|Boşanma) Kayıt No[:\s]?\d{6,10}\b'},
        {'subcategory': 'İkametgah Belgesi Referansı', 'pattern': r'\bİkametgah Belgesi No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Çalışma İzni Referans Numarası', 'pattern': r'\bÇalışma İzni No[:\s]?\d{6,10}\b'},
        {'subcategory': 'SGK Dosya Numarası', 'pattern': r'\bSGK Dosya No[:\s]?\d{10,15}\b'},
        {'subcategory': 'Emniyet Genel Müdürlüğü Belge Referansları', 'pattern': r'\bEGM Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Adalet Bakanlığı Sistem Referansları', 'pattern': r'\bUYAP No[:\s]?\d{10,20}\b'},
        {'subcategory': 'Maliye Bakanlığı Belge Referansları', 'pattern': r'\bMB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'E-devlet Kapısı Giriş Logları (Örnek)', 'pattern': r'\bE-Devlet Giriş IP[:\s]?(\d{1,3}\.){3}\d{1,3}\b'},
        {'subcategory': 'Kamu İhale Kurumu Referans Numarası', 'pattern': r'\bKİK No[:\s]?\d{6,10}\b'},
        {'subcategory': 'BTK Kayıt Numarası', 'pattern': r'\bBTK Kayıt No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Çevre ve Şehircilik Bakanlığı Belge Referansı', 'pattern': r'\bÇŞB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Tarım ve Orman Bakanlığı Belge Referansı', 'pattern': r'\bTOB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Sanayi ve Teknoloji Bakanlığı Belge Referansı', 'pattern': r'\bSTB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kültür ve Turizm Bakanlığı Belge Referansı', 'pattern': r'\bKTB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Dışişleri Bakanlığı Belge Referansı', 'pattern': r'\bDB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Enerji ve Tabii Kaynaklar Bakanlığı Belge Referansı', 'pattern': r'\bETKB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Ulaştırma ve Altyapı Bakanlığı Belge Referansı', 'pattern': r'\bUAB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'İçişleri Bakanlığı Belge Referansı', 'pattern': r'\bİİB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Milli Eğitim Bakanlığı Belge Referansı', 'pattern': r'\bMEB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Sağlık Bakanlığı Belge Referansı', 'pattern': r'\bSağlık Bakanlığı Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Aile ve Sosyal Hizmetler Bakanlığı Belge Referansı', 'pattern': r'\bASHB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Çalışma ve Sosyal Güvenlik Bakanlığı Belge Referansı', 'pattern': r'\bÇSGB Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Sanayi Sicil Belgesi Numarası', 'pattern': r'\bSanayi Sicil Belge No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Esnaf ve Sanatkar Sicil Numarası', 'pattern': r'\bEsnaf Sicil No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Dernek / Vakıf Sicil Numarası', 'pattern': r'\b(Dernek|Vakıf) Sicil No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Parti Üyelik Bilgileri', 'pattern': r'\b(Parti Üyeliği|Üyelik No)[:\s]?\d{6,10}\b'},
        {'subcategory': 'Sendika Üyelik Bilgileri', 'pattern': r'\b(Sendika Üyeliği|Üyelik No)[:\s]?\d{6,10}\b'},
        {'subcategory': 'Oda / Birlik Sicil Numarası (Örn: TMMOB)', 'pattern': r'\b(TMMOB|Oda|Birlik) Sicil No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu Kurumu Personel Kimlik Kartı No (Örnek)', 'pattern': r'\bKKK No[:\s]?[A-Z]{2}\d{6,10}\b'},
        {'subcategory': 'Devlet Memuru Disiplin Kayıtları Referansı', 'pattern': r'\bDisiplin Kayıt No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Resmi Gazete İlan Numarası', 'pattern': r'\bRG İlan No[:\s]?\d{6,10}\b'},
        {'subcategory': 'TBMM Resmi Yayın Referansları', 'pattern': r'\bTBMM Yayın No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu Denetçiliği Kurumu Başvuru Numarası', 'pattern': r'\bKDK Başvuru No[:\s]?\d{6,10}\b'},
        {'subcategory': 'BYEGM Sarı Basın Kartı Numarası', 'pattern': r'\bSarı Basın Kartı No[:\s]?\d{6,10}\b'},
        {'subcategory': 'RTÜK Lisans Numarası', 'pattern': r'\bRTÜK Lisans No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Rekabet Kurumu Dosya Numarası', 'pattern': r'\bRK Dosya No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu İhale Kanunu Referansları', 'pattern': r'\bKİK Kanun No[:\s]?\d{4,5}\b'},
        {'subcategory': 'Kamu Alımları Platformu Referansları', 'pattern': r'\bEKAP Referans No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Devlet Teşvikleri Referans Numarası', 'pattern': r'\bTeşvik No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu Zararı Tespit Raporları Referansı', 'pattern': r'\bKamu Zararı Rapor No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Sayıştay Rapor Referansları', 'pattern': r'\bSayıştay Rapor No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu Görevlileri Etik Kurulu Referansları', 'pattern': r'\bEtik Kurulu Referans No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu Taşınmazları Kayıt Bilgileri', 'pattern': r'\bTaşınmaz Kayıt No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu Personel Özlük Dosyası Referansları', 'pattern': r'\bÖzlük Dosya No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu Kurumu Yönetim Kurulu Karar Numarası', 'pattern': r'\bYönetim Kurulu Karar No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu Kurumu İç Denetim Raporları Referansı', 'pattern': r'\bİç Denetim Rapor No[:\s]?\d{6,10}\b'},
        {'subcategory': 'Kamu Kurumu Stratejik Plan Referansları', 'pattern': r'\bStratejik Plan Referans No[:\s]?\d{6,10}\b'}
    ]
}

# Regex pattern cache
_regex_pattern_cache = {}

def compile_regex_pattern(pattern_str):
    """Compile and cache regex pattern for better performance."""
    if pattern_str not in _regex_pattern_cache:
        try:
            _regex_pattern_cache[pattern_str] = re.compile(pattern_str)
        except re.error as e:
            print(f"Invalid regex pattern: {pattern_str} - {e}")
            return None
    return _regex_pattern_cache[pattern_str]

def validate_regex_pattern(pattern_str):
    """Validate regex pattern for security and correctness."""
    if not pattern_str or len(pattern_str) > 1000:  # Prevent extremely long patterns
        return False, "Pattern is empty or too long"
    
    # Check for potentially dangerous patterns
    dangerous_patterns = [
        r'\.\.\/',  # Directory traversal
        r'\/etc\/',  # System files
        r'\/var\/',  # System files
        r'\/root\/',  # Root directory
        r'\/proc\/',  # Process information
        r'\/sys\/',   # System information
        r'\/dev\/',   # Device files
        r'\/boot\/',  # Boot files
        r'\/bin\/',   # Binary files
        r'\/sbin\/',  # System binary files
    ]
    
    for dangerous in dangerous_patterns:
        if re.search(dangerous, pattern_str):
            return False, f"Pattern contains potentially dangerous path: {dangerous}"
    
    try:
        re.compile(pattern_str)
        return True, "Pattern is valid"
    except re.error as e:
        return False, f"Invalid regex pattern: {str(e)}"

def get_context_lines(file_path, line_number, context=3):
    """Get context lines around a specific line number from a file."""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
            
        start_line = max(0, line_number - context - 1)
        end_line = min(len(lines), line_number + context)
        
        context_lines = []
        for i in range(start_line, end_line):
            context_lines.append({
                'line_number': i + 1,
                'text': lines[i].rstrip('\n')
            })
            
        return context_lines
    except Exception as e:
        return [{'line_number': line_number, 'text': f'Error reading context: {str(e)}'}]

def should_scan_file(file_path):
    """Determine if a file should be scanned based on its extension"""
    text_extensions = {
        '.txt', '.log', '.md', '.rst', '.ini', '.conf', '.config', '.cfg',
        '.json', '.xml', '.yaml', '.yml', '.toml', '.csv', '.tsv',
        '.py', '.js', '.java', '.c', '.cpp', '.h', '.hpp', '.cs', '.php',
        '.rb', '.go', '.rs', '.swift', '.kt', '.ts', '.dart',
        '.html', '.htm', '.css', '.scss', '.sass', '.less',
        '.sql', '.sh', '.bash', '.bat', '.cmd', '.ps1',
        '.env', '.properties', '.config', '.cfg', '.ini',
        '.dockerfile', '.dockerignore', '.gitignore',
        '.editorconfig', '.eslintrc', '.prettierrc',
        '.babelrc', '.webpack', '.rollup', '.vscode',
        '.idea', '.eclipse', '.project', '.classpath',
        '.gradle', '.mvn', '.pom', '.sln', '.csproj',
        '.xcodeproj', '.pbxproj', '.plist', '.strings',
        '.xib', '.storyboard', '.nib', '.xcdatamodel',
        '.xcscheme', '.xcworkspace', '.xcuserstate',
        '.xcconfig', '.entitlements', '.mobileprovision',
        '.cer', '.p12', '.pem', '.key', '.crt', '.csr',
        '.der', '.p7b', '.p7c', '.pfx', '.p12', '.key',
        '.keystore', '.jks', '.truststore', '.jceks',
        '.bks', '.pem', '.crt', '.cer', '.der', '.p7b',
        '.p7c', '.pfx', '.p12', '.key', '.keystore',
        '.jks', '.truststore', '.jceks', '.bks',
        '.docx'  # Added support for Word documents
    }
    return os.path.splitext(file_path)[1].lower() in text_extensions 